name: GitHubStars to DuckDB
language: python
variables:
  - name: GH_TOKEN
    inputType: Secret
    description: GitHub token
    defaultValue: GH_TOKEN
    required: true
  - name: GH_ORG
    inputType: FreeText
    description: ''
    defaultValue: quixio
    required: false
  - name: sleeptime
    inputType: FreeText
    description: ''
    defaultValue: 21600
    required: false
  - name: GH_REPO
    inputType: FreeText
    description: ''
    defaultValue: quix-streams
    required: false
  - name: MOTHERDUCK_TOKEN
    inputType: Secret
    description: ''
    defaultValue: MD_TOKEN_DEVREL
    required: false
  - name: MOTHERDUCK_DATABASE
    inputType: FreeText
    description: ''
    defaultValue: ghstats
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
