name: GitHubStars to DuckDB
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: github_data_v1
    required: true
  - name: GH_TOKEN
    inputType: Secret
    description: GitHub token
    defaultValue: GH_TOKEN
    required: true
  - name: GH_ORG
    inputType: FreeText
    description: ''
    defaultValue: quixio
    required: false
  - name: sleeptime
    inputType: FreeText
    description: ''
    defaultValue: 3600
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
