name: Write Stats to DuckDB on MotherDuck
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: github_data_v1
    required: true
  - name: MOTHERDUCK_TOKEN
    inputType: Secret
    description: Authentication token to access InfluxDB.
    defaultValue: MD_TOKEN_DEVREL
    required: true
  - name: MOTHERDUCK_DATABASE
    inputType: FreeText
    description: Database name in InfluxDB where data should be stored.
    defaultValue: ghstats
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: The name of the consumer group to use when consuming from Kafka
    defaultValue: duckdb-sink-v4
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
