name: Write Stats to DuckDB on MotherDuck
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: input-data
    required: true
  - name: MOTHERDUCK_TOKEN
    inputType: Secret
    description: Authentication token to access InfluxDB.
    defaultValue: INFLUXDB_TOKEN
    required: true
  - name: INFLUXDB_DATABASE
    inputType: FreeText
    description: Database name in InfluxDB where data should be stored.
    defaultValue: ''
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: The name of the consumer group to use when consuming from Kafka
    defaultValue: influxdb-sink
    required: true
  - name: TIMESTAMP_COLUMN
    inputType: FreeText
    description: 'The column containing the timestamp column. NOTE: Must be nanoseconds'
    defaultValue: ''
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
